import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/ui/utils/cn"
import "../styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  fallback: ["system-ui", "Roboto", "sans-serif"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "font-inter antialiased bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400 min-h-screen min-w-full"
        )}
      >
          {children}
      </body>
    </html>
  );
}
